print("Bienvenido al programa,calculadora de ganancias para su empresa. ")
print("")
nombre1=input("Ingrese su Nombre: ",)
nombre2=input("Ingrese su Segundo Nombre: ",)
apellido1=input("Ingrese su primer Apellido: ",)
apellido2=input("Ingrese su Segundo Apellido: ",)
print("")
empresa=input("nombre de la Empresa: ")
print("")
print("")
print("Bienvenido al sistema ",nombre, nombre2, apellido1, apellido2 )
print("")
print("")
print(" Empresa:" + empresa )
print("")
print("")

GananciaEnero=int(input("Ingrese las ganancias de Enero: "))
GananciaFebrero=int(input("Ingrese las gananias de Febrero: "))
GanaciasMarzo=int(input("Ingrese las ganancias de Marzo: "))
print("")
print("")

ganaciastotales = GananciaEnero +GanaciaFebrero + GananciaMarzo
print("Las ganancias fueron de $:",gananciastotales)
print("")
print("")

print("Gracias por utilizar nuestros srvicios, lo esperamos pronto")
